### ISSUE TITLE
test/perf/test_send_recv 使用 gloo 报错

### ISSUE THREAD

**Issue by rmfrall** [flagos-ai/FlagCX#98]
测试使用gloo运行FlagCX/test/perf/test_sendrecv报错如下，还望麻烦看一下
```
root@ts-34:/data/FlagCX/test/perf# cat gloo-mpi.sh
export MPI_HOME=/usr/mpi/gcc/openmpi-4.1.7a1
export COREX_HOME=/usr/local/corex
export IXDCGMX_HOME=/usr/local/ixdcgm
export LD_LIBRARY_PATH=$MPI_HOME/lib:$IXDCGMX_HOME/lib64:$COREX_HOME/lib:$COREX_HOME/lib64:$LD_LIBRARY_PATH:/data/gloo/build/install/lib
export PATH=$MPI_HOME/bin:$IXDCGMX_HOME/bin:$COREX_HOME/bin:$PATH

export CUDA_DEVICE_MAX_CONNECTIONS=1
export GLOO_SOCKET_IFNAME=ens3f0np0
export FLAGCX_SOCKET_IFNAME=ens3f0np0
export NCCL_SOCKET_IFNAME=ens3f0np0
export FLAGCX_IB_HCA=mlx5_2:1
export NCCL_IB_HCA=mlx5_2:1
export FLAGCX_USENET=mlx5_2
export FLAGCX_USEDEV=1
export FLAGCX_DEBUG=TRACE
export FLAGCX_DEBUG_SUBSYS=ALL
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=ALL
export USE_BOOTSTRAP_CCL=1
export FLAGCX_USE_HOST_COMM=1

/data/FlagCX/test/perf/test_sendrecv


root@ts-34:/data/FlagCX/test/perf# mpirun --allow-run-as-root  --host "10.0.10.34:1,10.0.10.35:1" -np 2 bash /data/FlagCX/test/perf/gloo-mpi.sh

Authorized users only. All activities may be monitored and reported.
I am 0 of 2
I am 1 of 2
ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_SOCKET_IFNAME set by environment to ens3f0np0
ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_SOCKET_IFNAME set to ens3f0np0
ts-34:1304096:1304096 [0] 0.884546 findInterfaces:128 FLAGCX TRACE Found interface lo:127.0.0.1<0>
ts-34:1304096:1304096 [0] 0.904224 findInterfaces:128 FLAGCX TRACE Found interface ens64f0:172.27.13.34<0>
ts-34:1304096:1304096 [0] 0.908202 findInterfaces:128 FLAGCX TRACE Found interface ens3f0np0:10.0.10.34<0>
ts-34:1304096:1304096 [0] FLAGCX INFO Bootstrap : Using ens3f0np0:10.0.10.34<0>
ts-34:1304096:1304096 [0] 0.960969 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<50687>
ts-34:1304096:1304966 [0] 1.074400 bootstrapRoot:125 FLAGCX TRACE BEGIN
ts-34:1304096:1304096 [0] 128.980849 bootstrapInit:239 FLAGCX TRACE rank 0 nranks 2
ts-34:1304096:1304096 [0] 128.993352 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<59873>
ts-34:1304096:1304096 [0] 129.001996 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<33947>
ts-34:1304096:1304096 [0] 129.009552 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<50687>
ts-34:1304096:1304966 [0] FLAGCX INFO Bootstrap Root : rank 0 of 2 ranks checked in
ts-34:1304096:1304966 [0] 129.192669 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 0 total 1/2
ts-34:1304096:1304966 [0] FLAGCX INFO Bootstrap Root : rank 1 of 2 ranks checked in
ts-34:1304096:1304966 [0] 224.267105 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 1 total 2/2
ts-34:1304096:1304966 [0] 224.269537 bootstrapRoot:159 FLAGCX TRACE COLLECTED ALL 2 HANDLES
ts-34:1304096:1304966 [0] 224.276083 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<33947>
ts-34:1304096:1304096 [0] 224.390991 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
ts-34:1304096:1304966 [0] 224.408886 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<60499>
ts-34:1304096:1304966 [0] FLAGCX INFO SENT OUT ALL 2 HANDLES
ts-34:1304096:1304966 [0] 224.613924 bootstrapRoot:182 FLAGCX TRACE DONE
ts-34:1304096:1304096 [0] 224.710629 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 28
ts-34:1304096:1304096 [0] 224.772287 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 28 - DONE
ts-34:1304096:1304096 [0] FLAGCX INFO rank 0 nranks 2 - DONE
ts-34:1304096:1304096 [0] 224.792701 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 128
ts-34:1304096:1304096 [0] 224.838100 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 128 - DONE
ts-34:1304096:1304096 [0] 224.856483 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
ts-34:1304096:1304096 [0] 224.862504 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 224.885809 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
ts-34:1304096:1304096 [0] 225.051437 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 225.070911 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
ts-34:1304096:1304096 [0] 225.084221 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
ts-34:1304096:1304096 [0] 225.189958 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 4
ts-34:1304096:1304096 [0] 225.225059 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 4 - DONE
ts-34:1304096:1304096 [0] 225.229317 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 4
ts-34:1304096:1304096 [0] 225.267115 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 4 - DONE
ts-34:1304096:1304096 [0] 225.270917 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 4
ts-34:1304096:1304096 [0] 225.302661 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 4 - DONE
ts-34:1304096:1304096 [0] 225.306514 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
ts-34:1304096:1304096 [0] 225.308607 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 225.316931 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
ts-34:1304096:1304096 [0] 225.418628 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 225.461204 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
ts-34:1304096:1304096 [0] 225.473343 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
ts-34:1304096:1304096 [0] FLAGCX INFO rank = 0, nranks = 2, nclusters = 2, cluster_id = 0, cluster_size = 1, cluster_inter_rank = 0, homo_rank = 0, homo_root_rank = 0, homo_inter_rank = 0, homo_ranks = 1
ts-34:1304096:1304096 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ens3f0np0
ts-34:1304096:1304096 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ens3f0np0
ts-34:1304096:1304096 [0] NCCL INFO Bootstrap : Using ens3f0np0:10.0.10.34<0>
ts-34:1304096:1304096 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
ts-34:1304096:1304096 [0] 226.569651 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 256
ts-34:1304096:1304096 [0] 227.460546 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 256 - DONE
ts-34:1304096:1304096 [0] 227.464587 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
ts-34:1304096:1304096 [0] 227.466706 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 227.473655 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
ts-34:1304096:1304096 [0] 227.602506 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 227.638591 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
ts-34:1304096:1304096 [0] 227.650259 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
ts-34:1304096:1304096 [0] NCCL INFO cudaDriverVersion 10020
NCCL version 2.14.3+cuda10.2
ts-34:1304096:1304096 [0] NCCL INFO init.cc:1325 Cuda Host Alloc leak Size 4 pointer 0x7fc4b2ffb000
ts-34:1304096:1304096 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ens3f0np0
ts-34:1304096:1304096 [0] NCCL INFO NCCL_IB_HCA set to mlx5_2:1
ts-34:1304096:1304096 [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE [RO]; OOB ens3f0np0:10.0.10.34<0>
ts-34:1304096:1304096 [0] NCCL INFO Using network IB
ts-34:1304096:1304096 [0] NCCL INFO init.cc:377 Cuda Host Alloc Size 3964928 pointer 0x7c4406435000
ts-34:1304096:1304096 [0] NCCL INFO init.cc:378 Cuda Host Alloc Size 2490368 pointer 0x7c44061d5000
ts-34:1304096:1304096 [0] NCCL INFO init.cc:382 Cuda Alloc Size 1179648 pointer 0x7e448f400000
ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:610 Ib Alloc Size 26560 pointer 0x5648b567b000
ts-34:1304096:1304096 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 29136 mtu 5 GID 0 (80FE/825F6CFEFFD3EBEA)
ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:667 Ib Alloc Size 552 pointer 0x5648b5692000
ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:697 Ib Alloc Size 21688 pointer 0x5648b56ea000
ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:710 Ib Alloc Size 552 pointer 0x5648b5694000
ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:785 Ib Alloc Size 552 pointer 0x5648b570a000
ts-34:1304096:1304096 [0] NCCL INFO Mem Realloc old size 0, new size 768 pointer 0x5648b4d567d0
ts-34:1304096:1304096 [0] NCCL INFO Mem Realloc old size 0, new size 768 pointer 0x5648b4d567d0
ts-34:1304096:1304096 [0] NCCL INFO Topo/Plugin: libnccl-topo.so is not used
ts-34:1304096:1304096 [0] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 0 'mlx5_2'
ts-34:1304096:1304096 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 11000 / HCA 0 (distance 4 <= 7), read 0
ts-34:1304096:1304096 [0] NCCL INFO === System : maxBw 5000.0 totalBw 0.0 ===
ts-34:1304096:1304096 [0] NCCL INFO CPU/0 (1/1/2)
ts-34:1304096:1304096 [0] NCCL INFO + PCI[48.0] - PCI/B000 (1000c0301000100b)
ts-34:1304096:1304096 [0] NCCL INFO               + PCI[24.0] - PCI/D000 (1000c01010000000)
ts-34:1304096:1304096 [0] NCCL INFO                             + PCI[24.0] - GPU/11000 (0)
ts-34:1304096:1304096 [0] NCCL INFO               + PCI[24.0] - NIC/20000
ts-34:1304096:1304096 [0] NCCL INFO ==========================================
ts-34:1304096:1304096 [0] NCCL INFO GPU/11000 :GPU/11000 (0/5000.000000/LOC) CPU/0 (3/24.000000/PHB)
ts-34:1304096:1304096 [0] NCCL INFO Setting affinity for GPU 0 to 01,00000000,00000000,00000001
ts-34:1304096:1304096 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 16, bw 44.000000/44.000000, type LOC/PIX, sameChannels 1
ts-34:1304096:1304096 [0] NCCL INFO  0 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  1 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  2 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  3 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  4 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  5 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  6 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  7 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  8 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  9 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 10 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 11 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 12 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 13 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 14 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 15 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 16, bw 44.000000/44.000000, type LOC/PIX, sameChannels 1
ts-34:1304096:1304096 [0] NCCL INFO  0 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  1 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  2 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  3 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  4 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  5 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  6 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  7 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  8 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  9 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 10 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 11 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 12 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 13 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 14 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 15 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 16, bw 44.000000/44.000000, type LOC/PIX, sameChannels 1
ts-34:1304096:1304096 [0] NCCL INFO  0 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  1 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  2 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  3 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  4 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  5 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  6 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  7 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  8 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO  9 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 10 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 11 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 12 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 13 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 14 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO 15 : GPU/0
ts-34:1304096:1304096 [0] NCCL INFO Tree 0 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 16 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 1 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 17 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 2 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 18 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 3 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 19 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 4 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 20 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 5 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 21 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 6 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 22 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 7 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 23 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 8 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 24 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 9 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 25 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 10 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 26 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 11 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 27 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 12 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 28 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 13 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 29 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 14 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 30 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 15 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Tree 31 : -1 -> 0 -> -1/-1/-1
ts-34:1304096:1304096 [0] NCCL INFO Channel 00/01 :    0
ts-34:1304096:1304096 [0] NCCL INFO Ring 00 : 0 -> 0 -> 0
ts-34:1304096:1304096 [0] NCCL INFO Trees [0] -1/-1/-1->0->1
ts-34:1304096:1304096 [0] NCCL INFO misc/utils.cc:235 memory stack hunk malloc(65536)
ts-34:1304096:1304096 [0] NCCL INFO channel.cc:23 Cuda Alloc Size 768 pointer 0x7e448f520000
ts-34:1304096:1304096 [0] NCCL INFO channel.cc:27 Cuda Alloc Size 4 pointer 0x7e448f521000
ts-34:1304096:1304096 [0] NCCL INFO Connected all rings
ts-34:1304096:1304096 [0] NCCL INFO Connected all trees
ts-34:1304096:1304096 [0] NCCL INFO 1 coll channels, 1 p2p channels, 1 p2p channels per peer
ts-34:1304096:1304971 [0] NCCL INFO Mem Realloc old size 0, new size 8 pointer 0x5648b55f89c0
ts-34:1304096:1304971 [0] NCCL INFO Allocated 524640 bytes of shared memory in /dev/shm/nccl-TSIjjk

ts-34:1304096:1304971 [0] NCCL INFO New proxy send connection 0 from local rank 0, transport 2
ts-34:1304096:1304096 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7c4408002210
ts-34:1304096:1304096 [0] NCCL INFO Allocated 16777216 bytes of shared memory in /dev/shm/nccl-bZzYPl

ts-34:1304096:1304971 [0] NCCL INFO transport/net.cc:395 Cuda Alloc Size 16777216 pointer 0x7e448f522000
ts-34:1304096:1304096 [0] NCCL INFO init.cc:1188 Cuda Alloc Size 16384 pointer 0x7e4490522000
ts-34:1304096:1304096 [0] NCCL INFO init.cc:423 Cuda Alloc Size 8256 pointer 0x7e4490526000
ts-34:1304096:1304096 [0] NCCL INFO init.cc:448 Cuda Host Alloc Size 39845888 pointer 0x7c43fda00000
ts-34:1304096:1304096 [0] NCCL INFO init.cc:454 Cuda Host Alloc Size 128 pointer 0x7c440c04b000
ts-34:1304096:1304096 [0] NCCL INFO comm 0x5648b5610a00 rank 0 nranks 1 cudaDev 0 busId 11000 - Init COMPLETE
ts-34:1304096:1304096 [0] 397.403340 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<36025>
ts-34:1304096:1304096 [0] 397.454292 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 256
ts-34:1304096:1304973 [0] 397.477458 bootstrapRoot:125 FLAGCX TRACE BEGIN
ts-34:1304096:1304096 [0] 397.530027 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 256 - DONE
ts-34:1304096:1304096 [0] 397.534616 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
ts-34:1304096:1304096 [0] 397.536991 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 397.543707 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
ts-34:1304096:1304096 [0] 397.785858 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
ts-34:1304096:1304096 [0] 397.808074 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
ts-34:1304096:1304096 [0] 397.819508 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
ts-34:1304096:1304096 [0] 397.832907 bootstrapInit:239 FLAGCX TRACE rank 0 nranks 2
ts-34:1304096:1304096 [0] 397.840894 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<42305>
ts-34:1304096:1304096 [0] 397.848657 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<43683>
ts-34:1304096:1304096 [0] 397.854202 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<36025>
ts-34:1304096:1304973 [0] FLAGCX INFO Bootstrap Root : rank 0 of 2 ranks checked in
ts-34:1304096:1304973 [0] 397.989226 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 0 total 1/2
ts-34:1304096:1304973 [0] FLAGCX INFO Bootstrap Root : rank 1 of 2 ranks checked in
ts-34:1304096:1304973 [0] 398.028867 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 1 total 2/2
ts-34:1304096:1304973 [0] 398.031184 bootstrapRoot:159 FLAGCX TRACE COLLECTED ALL 2 HANDLES
ts-34:1304096:1304973 [0] 398.038578 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<43683>
ts-34:1304096:1304096 [0] 398.150102 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<60563>
ts-34:1304096:1304973 [0] 398.166563 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<44073>
ts-34:1304096:1304973 [0] FLAGCX INFO SENT OUT ALL 2 HANDLES
ts-34:1304096:1304973 [0] 398.296969 bootstrapRoot:182 FLAGCX TRACE DONE
ts-34:1304096:1304096 [0] 398.587792 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 28
ts-34:1304096:1304096 [0] 398.709504 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 28 - DONE
ts-34:1304096:1304096 [0] FLAGCX INFO rank 0 nranks 2 - DONE
ts-34:1304096:1304096 [0] 398.793327 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<57451>
ts-34:1304096:1304096 [0] 398.800088 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<57451>
ts-34:1304096:1304974 [0] FLAGCX INFO proxy msg : Proxy: 0
ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_SOCKET_IFNAME set by environment to ens3f0np0
ts-34:1304096:1304096 [0] 399.995178 findInterfaces:128 FLAGCX TRACE Found interface lo:127.0.0.1<0>
ts-34:1304096:1304096 [0] 400.004199 findInterfaces:128 FLAGCX TRACE Found interface ens64f0:172.27.13.34<0>
ts-34:1304096:1304096 [0] 400.007848 findInterfaces:128 FLAGCX TRACE Found interface ens3f0np0:10.0.10.34<0>
ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_IB_HCA set to mlx5_2:1
ts-34:1304096:1304096 [0] 420.577577 flagcxIbInit:545 FLAGCX TRACE NET/IB: [2] mlx5_2:uverbs2:1/RoCE speed=100000 context=0x5648b5743d80 pciPath=/sys/devices/pci0000:0a/0000:0a:01.0/0000:0b:00.0/0000:0c:03.0/0000:20:00.0 ar=0
ts-34:1304096:1304096 [0] FLAGCX INFO NET/IB : Using [0]mlx5_2:1/RoCE [RO]; OOB ens3f0np0:10.0.10.34<0>
ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_TOPO_FILE environment variable not set
ts-34:1304096:1304096 [0] FLAGCX INFO did not find local net for apu 0 in xml topo
ts-34:1304096:1304096 [0] FLAGCX INFO APU 0 use net mlx5_2 specified in FLAGCX_USENET environment variable.
[ts-34:1304096:0:1304096] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x60014eeeeef02)
==== backtrace (tid:1304096) ====
 0  /lib/libucs.so.0(ucs_handle_error+0x2e4) [0x7fc4b2edfa84]
 1  /lib/libucs.so.0(+0x23aac) [0x7fc4b2ee0aac]
 2  /lib/libucs.so.0(+0x23c6a) [0x7fc4b2ee0c6a]
 3  /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp16CreateDeviceAttrERKNS1_4attrE+0x2a5) [0x7fc4b4f80865]
 4  /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp12CreateDeviceERKNS1_4attrE+0x36) [0x7fc4b4f82c16]
 5  ../../build/lib/libflagcx.so(_Z23glooAdaptorCommInitRankPP15flagcxInnerCommiP14flagcxUniqueIdiP14bootstrapState+0x224) [0x7fc4ca358088]
 6  ../../build/lib/libflagcx.so(flagcxCommInitRank+0x1831) [0x7fc4ca3242b4]
 7  /data/FlagCX/test/perf/test_sendrecv(+0x2684) [0x5648875d5684]
 8  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc4c9d8cd90]
 9  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fc4c9d8ce40]
10  /data/FlagCX/test/perf/test_sendrecv(+0x23c5) [0x5648875d53c5]
=================================
[ts-34:1304096] *** Process received signal ***
[ts-34:1304096] Signal: Segmentation fault (11)
[ts-34:1304096] Signal code:  (-6)
[ts-34:1304096] Failing at address: 0x13e620
[ts-34:1304096] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fc4c9da5520]
[ts-34:1304096] [ 1] /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp16CreateDeviceAttrERKNS1_4attrE+0x2a5)[0x7fc4b4f80865]
[ts-34:1304096] [ 2] /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp12CreateDeviceERKNS1_4attrE+0x36)[0x7fc4b4f82c16]
[ts-34:1304096] [ 3] ../../build/lib/libflagcx.so(_Z23glooAdaptorCommInitRankPP15flagcxInnerCommiP14flagcxUniqueIdiP14bootstrapState+0x224)[0x7fc4ca358088]
[ts-34:1304096] [ 4] ../../build/lib/libflagcx.so(flagcxCommInitRank+0x1831)[0x7fc4ca3242b4]
[ts-34:1304096] [ 5] /data/FlagCX/test/perf/test_sendrecv(+0x2684)[0x5648875d5684]
[ts-34:1304096] [ 6] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fc4c9d8cd90]
[ts-34:1304096] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fc4c9d8ce40]
[ts-34:1304096] [ 8] /data/FlagCX/test/perf/test_sendrecv(+0x23c5)[0x5648875d53c5]
[ts-34:1304096] *** End of error message ***
/data/FlagCX/test/perf/gloo-mpi.sh: line 23: 1304096 Segmentation fault      (core dumped) /data/FlagCX/test/perf/test_sendrecv
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[35823,1],0]
  Exit code:    139
--------------------------------------------------------------------------

```

**Comment by MC952-arch** [comment]
尝试添加export FLAGCX_GLOO_SOCKET_IFNAME=ens3f0np0

**Comment by MC952-arch** [comment]
> 测试使用gloo运行FlagCX/test/perf/test_sendrecv报错如下，还望麻烦看一下
> 
> ```
> root@ts-34:/data/FlagCX/test/perf# cat gloo-mpi.sh
> export MPI_HOME=/usr/mpi/gcc/openmpi-4.1.7a1
> export COREX_HOME=/usr/local/corex
> export IXDCGMX_HOME=/usr/local/ixdcgm
> export LD_LIBRARY_PATH=$MPI_HOME/lib:$IXDCGMX_HOME/lib64:$COREX_HOME/lib:$COREX_HOME/lib64:$LD_LIBRARY_PATH:/data/gloo/build/install/lib
> export PATH=$MPI_HOME/bin:$IXDCGMX_HOME/bin:$COREX_HOME/bin:$PATH
> 
> export CUDA_DEVICE_MAX_CONNECTIONS=1
> export GLOO_SOCKET_IFNAME=ens3f0np0
> export FLAGCX_SOCKET_IFNAME=ens3f0np0
> export NCCL_SOCKET_IFNAME=ens3f0np0
> export FLAGCX_IB_HCA=mlx5_2:1
> export NCCL_IB_HCA=mlx5_2:1
> export FLAGCX_USENET=mlx5_2
> export FLAGCX_USEDEV=1
> export FLAGCX_DEBUG=TRACE
> export FLAGCX_DEBUG_SUBSYS=ALL
> export NCCL_DEBUG=INFO
> export NCCL_DEBUG_SUBSYS=ALL
> export USE_BOOTSTRAP_CCL=1
> export FLAGCX_USE_HOST_COMM=1
> 
> /data/FlagCX/test/perf/test_sendrecv
> 
> 
> root@ts-34:/data/FlagCX/test/perf# mpirun --allow-run-as-root  --host "10.0.10.34:1,10.0.10.35:1" -np 2 bash /data/FlagCX/test/perf/gloo-mpi.sh
> 
> Authorized users only. All activities may be monitored and reported.
> I am 0 of 2
> I am 1 of 2
> ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_SOCKET_IFNAME set by environment to ens3f0np0
> ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_SOCKET_IFNAME set to ens3f0np0
> ts-34:1304096:1304096 [0] 0.884546 findInterfaces:128 FLAGCX TRACE Found interface lo:127.0.0.1<0>
> ts-34:1304096:1304096 [0] 0.904224 findInterfaces:128 FLAGCX TRACE Found interface ens64f0:172.27.13.34<0>
> ts-34:1304096:1304096 [0] 0.908202 findInterfaces:128 FLAGCX TRACE Found interface ens3f0np0:10.0.10.34<0>
> ts-34:1304096:1304096 [0] FLAGCX INFO Bootstrap : Using ens3f0np0:10.0.10.34<0>
> ts-34:1304096:1304096 [0] 0.960969 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<50687>
> ts-34:1304096:1304966 [0] 1.074400 bootstrapRoot:125 FLAGCX TRACE BEGIN
> ts-34:1304096:1304096 [0] 128.980849 bootstrapInit:239 FLAGCX TRACE rank 0 nranks 2
> ts-34:1304096:1304096 [0] 128.993352 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<59873>
> ts-34:1304096:1304096 [0] 129.001996 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<33947>
> ts-34:1304096:1304096 [0] 129.009552 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<50687>
> ts-34:1304096:1304966 [0] FLAGCX INFO Bootstrap Root : rank 0 of 2 ranks checked in
> ts-34:1304096:1304966 [0] 129.192669 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 0 total 1/2
> ts-34:1304096:1304966 [0] FLAGCX INFO Bootstrap Root : rank 1 of 2 ranks checked in
> ts-34:1304096:1304966 [0] 224.267105 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 1 total 2/2
> ts-34:1304096:1304966 [0] 224.269537 bootstrapRoot:159 FLAGCX TRACE COLLECTED ALL 2 HANDLES
> ts-34:1304096:1304966 [0] 224.276083 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<33947>
> ts-34:1304096:1304096 [0] 224.390991 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
> ts-34:1304096:1304966 [0] 224.408886 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<60499>
> ts-34:1304096:1304966 [0] FLAGCX INFO SENT OUT ALL 2 HANDLES
> ts-34:1304096:1304966 [0] 224.613924 bootstrapRoot:182 FLAGCX TRACE DONE
> ts-34:1304096:1304096 [0] 224.710629 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 28
> ts-34:1304096:1304096 [0] 224.772287 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 28 - DONE
> ts-34:1304096:1304096 [0] FLAGCX INFO rank 0 nranks 2 - DONE
> ts-34:1304096:1304096 [0] 224.792701 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 128
> ts-34:1304096:1304096 [0] 224.838100 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 128 - DONE
> ts-34:1304096:1304096 [0] 224.856483 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
> ts-34:1304096:1304096 [0] 224.862504 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 224.885809 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
> ts-34:1304096:1304096 [0] 225.051437 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 225.070911 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
> ts-34:1304096:1304096 [0] 225.084221 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
> ts-34:1304096:1304096 [0] 225.189958 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 4
> ts-34:1304096:1304096 [0] 225.225059 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 4 - DONE
> ts-34:1304096:1304096 [0] 225.229317 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 4
> ts-34:1304096:1304096 [0] 225.267115 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 4 - DONE
> ts-34:1304096:1304096 [0] 225.270917 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 4
> ts-34:1304096:1304096 [0] 225.302661 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 4 - DONE
> ts-34:1304096:1304096 [0] 225.306514 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
> ts-34:1304096:1304096 [0] 225.308607 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 225.316931 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
> ts-34:1304096:1304096 [0] 225.418628 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 225.461204 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
> ts-34:1304096:1304096 [0] 225.473343 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
> ts-34:1304096:1304096 [0] FLAGCX INFO rank = 0, nranks = 2, nclusters = 2, cluster_id = 0, cluster_size = 1, cluster_inter_rank = 0, homo_rank = 0, homo_root_rank = 0, homo_inter_rank = 0, homo_ranks = 1
> ts-34:1304096:1304096 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ens3f0np0
> ts-34:1304096:1304096 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ens3f0np0
> ts-34:1304096:1304096 [0] NCCL INFO Bootstrap : Using ens3f0np0:10.0.10.34<0>
> ts-34:1304096:1304096 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
> ts-34:1304096:1304096 [0] 226.569651 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 256
> ts-34:1304096:1304096 [0] 227.460546 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 256 - DONE
> ts-34:1304096:1304096 [0] 227.464587 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
> ts-34:1304096:1304096 [0] 227.466706 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 227.473655 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
> ts-34:1304096:1304096 [0] 227.602506 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 227.638591 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
> ts-34:1304096:1304096 [0] 227.650259 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
> ts-34:1304096:1304096 [0] NCCL INFO cudaDriverVersion 10020
> NCCL version 2.14.3+cuda10.2
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:1325 Cuda Host Alloc leak Size 4 pointer 0x7fc4b2ffb000
> ts-34:1304096:1304096 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ens3f0np0
> ts-34:1304096:1304096 [0] NCCL INFO NCCL_IB_HCA set to mlx5_2:1
> ts-34:1304096:1304096 [0] NCCL INFO NET/IB : Using [0]mlx5_2:1/RoCE [RO]; OOB ens3f0np0:10.0.10.34<0>
> ts-34:1304096:1304096 [0] NCCL INFO Using network IB
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:377 Cuda Host Alloc Size 3964928 pointer 0x7c4406435000
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:378 Cuda Host Alloc Size 2490368 pointer 0x7c44061d5000
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:382 Cuda Alloc Size 1179648 pointer 0x7e448f400000
> ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:610 Ib Alloc Size 26560 pointer 0x5648b567b000
> ts-34:1304096:1304096 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 29136 mtu 5 GID 0 (80FE/825F6CFEFFD3EBEA)
> ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:667 Ib Alloc Size 552 pointer 0x5648b5692000
> ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:697 Ib Alloc Size 21688 pointer 0x5648b56ea000
> ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:710 Ib Alloc Size 552 pointer 0x5648b5694000
> ts-34:1304096:1304096 [0] NCCL INFO transport/net_ib.cc:785 Ib Alloc Size 552 pointer 0x5648b570a000
> ts-34:1304096:1304096 [0] NCCL INFO Mem Realloc old size 0, new size 768 pointer 0x5648b4d567d0
> ts-34:1304096:1304096 [0] NCCL INFO Mem Realloc old size 0, new size 768 pointer 0x5648b4d567d0
> ts-34:1304096:1304096 [0] NCCL INFO Topo/Plugin: libnccl-topo.so is not used
> ts-34:1304096:1304096 [0] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 0 'mlx5_2'
> ts-34:1304096:1304096 [0] NCCL INFO GPU Direct RDMA Enabled for GPU 11000 / HCA 0 (distance 4 <= 7), read 0
> ts-34:1304096:1304096 [0] NCCL INFO === System : maxBw 5000.0 totalBw 0.0 ===
> ts-34:1304096:1304096 [0] NCCL INFO CPU/0 (1/1/2)
> ts-34:1304096:1304096 [0] NCCL INFO + PCI[48.0] - PCI/B000 (1000c0301000100b)
> ts-34:1304096:1304096 [0] NCCL INFO               + PCI[24.0] - PCI/D000 (1000c01010000000)
> ts-34:1304096:1304096 [0] NCCL INFO                             + PCI[24.0] - GPU/11000 (0)
> ts-34:1304096:1304096 [0] NCCL INFO               + PCI[24.0] - NIC/20000
> ts-34:1304096:1304096 [0] NCCL INFO ==========================================
> ts-34:1304096:1304096 [0] NCCL INFO GPU/11000 :GPU/11000 (0/5000.000000/LOC) CPU/0 (3/24.000000/PHB)
> ts-34:1304096:1304096 [0] NCCL INFO Setting affinity for GPU 0 to 01,00000000,00000000,00000001
> ts-34:1304096:1304096 [0] NCCL INFO Pattern 4, crossNic 0, nChannels 16, bw 44.000000/44.000000, type LOC/PIX, sameChannels 1
> ts-34:1304096:1304096 [0] NCCL INFO  0 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  1 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  2 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  3 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  4 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  5 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  6 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  7 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  8 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  9 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 10 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 11 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 12 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 13 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 14 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 15 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 16, bw 44.000000/44.000000, type LOC/PIX, sameChannels 1
> ts-34:1304096:1304096 [0] NCCL INFO  0 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  1 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  2 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  3 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  4 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  5 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  6 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  7 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  8 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  9 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 10 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 11 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 12 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 13 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 14 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 15 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO Pattern 3, crossNic 0, nChannels 16, bw 44.000000/44.000000, type LOC/PIX, sameChannels 1
> ts-34:1304096:1304096 [0] NCCL INFO  0 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  1 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  2 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  3 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  4 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  5 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  6 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  7 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  8 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO  9 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 10 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 11 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 12 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 13 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 14 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO 15 : GPU/0
> ts-34:1304096:1304096 [0] NCCL INFO Tree 0 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 16 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 1 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 17 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 2 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 18 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 3 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 19 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 4 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 20 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 5 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 21 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 6 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 22 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 7 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 23 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 8 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 24 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 9 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 25 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 10 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 26 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 11 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 27 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 12 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 28 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 13 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 29 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 14 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 30 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 15 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Tree 31 : -1 -> 0 -> -1/-1/-1
> ts-34:1304096:1304096 [0] NCCL INFO Channel 00/01 :    0
> ts-34:1304096:1304096 [0] NCCL INFO Ring 00 : 0 -> 0 -> 0
> ts-34:1304096:1304096 [0] NCCL INFO Trees [0] -1/-1/-1->0->1
> ts-34:1304096:1304096 [0] NCCL INFO misc/utils.cc:235 memory stack hunk malloc(65536)
> ts-34:1304096:1304096 [0] NCCL INFO channel.cc:23 Cuda Alloc Size 768 pointer 0x7e448f520000
> ts-34:1304096:1304096 [0] NCCL INFO channel.cc:27 Cuda Alloc Size 4 pointer 0x7e448f521000
> ts-34:1304096:1304096 [0] NCCL INFO Connected all rings
> ts-34:1304096:1304096 [0] NCCL INFO Connected all trees
> ts-34:1304096:1304096 [0] NCCL INFO 1 coll channels, 1 p2p channels, 1 p2p channels per peer
> ts-34:1304096:1304971 [0] NCCL INFO Mem Realloc old size 0, new size 8 pointer 0x5648b55f89c0
> ts-34:1304096:1304971 [0] NCCL INFO Allocated 524640 bytes of shared memory in /dev/shm/nccl-TSIjjk
> 
> ts-34:1304096:1304971 [0] NCCL INFO New proxy send connection 0 from local rank 0, transport 2
> ts-34:1304096:1304096 [0] NCCL INFO Connection to proxy localRank 0 -> connection 0x7c4408002210
> ts-34:1304096:1304096 [0] NCCL INFO Allocated 16777216 bytes of shared memory in /dev/shm/nccl-bZzYPl
> 
> ts-34:1304096:1304971 [0] NCCL INFO transport/net.cc:395 Cuda Alloc Size 16777216 pointer 0x7e448f522000
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:1188 Cuda Alloc Size 16384 pointer 0x7e4490522000
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:423 Cuda Alloc Size 8256 pointer 0x7e4490526000
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:448 Cuda Host Alloc Size 39845888 pointer 0x7c43fda00000
> ts-34:1304096:1304096 [0] NCCL INFO init.cc:454 Cuda Host Alloc Size 128 pointer 0x7c440c04b000
> ts-34:1304096:1304096 [0] NCCL INFO comm 0x5648b5610a00 rank 0 nranks 1 cudaDev 0 busId 11000 - Init COMPLETE
> ts-34:1304096:1304096 [0] 397.403340 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<36025>
> ts-34:1304096:1304096 [0] 397.454292 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 256
> ts-34:1304096:1304973 [0] 397.477458 bootstrapRoot:125 FLAGCX TRACE BEGIN
> ts-34:1304096:1304096 [0] 397.530027 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 256 - DONE
> ts-34:1304096:1304096 [0] 397.534616 bootstrapIntraNodeBarrier:743 FLAGCX TRACE rank 0 nranks 2 tag 0 - ENTER
> ts-34:1304096:1304096 [0] 397.536991 bootstrapSend:317 FLAGCX TRACE Sending to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 397.543707 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<36139>
> ts-34:1304096:1304096 [0] 397.785858 bootstrapSend:321 FLAGCX TRACE Sent to peer=1 tag=0 size=4
> ts-34:1304096:1304096 [0] 397.808074 bootstrapRecv:412 FLAGCX TRACE Receiving tag=0 peer=1 size=4
> ts-34:1304096:1304096 [0] 397.819508 bootstrapIntraNodeBarrier:758 FLAGCX TRACE rank 0 nranks 2 tag 0 - DONE
> ts-34:1304096:1304096 [0] 397.832907 bootstrapInit:239 FLAGCX TRACE rank 0 nranks 2
> ts-34:1304096:1304096 [0] 397.840894 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<42305>
> ts-34:1304096:1304096 [0] 397.848657 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<43683>
> ts-34:1304096:1304096 [0] 397.854202 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<36025>
> ts-34:1304096:1304973 [0] FLAGCX INFO Bootstrap Root : rank 0 of 2 ranks checked in
> ts-34:1304096:1304973 [0] 397.989226 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 0 total 1/2
> ts-34:1304096:1304973 [0] FLAGCX INFO Bootstrap Root : rank 1 of 2 ranks checked in
> ts-34:1304096:1304973 [0] 398.028867 bootstrapRoot:157 FLAGCX TRACE Received connect from rank 1 total 2/2
> ts-34:1304096:1304973 [0] 398.031184 bootstrapRoot:159 FLAGCX TRACE COLLECTED ALL 2 HANDLES
> ts-34:1304096:1304973 [0] 398.038578 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<43683>
> ts-34:1304096:1304096 [0] 398.150102 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<60563>
> ts-34:1304096:1304973 [0] 398.166563 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.35<44073>
> ts-34:1304096:1304973 [0] FLAGCX INFO SENT OUT ALL 2 HANDLES
> ts-34:1304096:1304973 [0] 398.296969 bootstrapRoot:182 FLAGCX TRACE DONE
> ts-34:1304096:1304096 [0] 398.587792 bootstrapAllGather:467 FLAGCX TRACE rank 0 nranks 2 size 28
> ts-34:1304096:1304096 [0] 398.709504 bootstrapAllGather:471 FLAGCX TRACE rank 0 nranks 2 size 28 - DONE
> ts-34:1304096:1304096 [0] FLAGCX INFO rank 0 nranks 2 - DONE
> ts-34:1304096:1304096 [0] 398.793327 flagcxSocketListen:393 FLAGCX TRACE Listening on socket 10.0.10.34<57451>
> ts-34:1304096:1304096 [0] 398.800088 flagcxSocketConnect:620 FLAGCX TRACE Connecting to socket 10.0.10.34<57451>
> ts-34:1304096:1304974 [0] FLAGCX INFO proxy msg : Proxy: 0
> ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_SOCKET_IFNAME set by environment to ens3f0np0
> ts-34:1304096:1304096 [0] 399.995178 findInterfaces:128 FLAGCX TRACE Found interface lo:127.0.0.1<0>
> ts-34:1304096:1304096 [0] 400.004199 findInterfaces:128 FLAGCX TRACE Found interface ens64f0:172.27.13.34<0>
> ts-34:1304096:1304096 [0] 400.007848 findInterfaces:128 FLAGCX TRACE Found interface ens3f0np0:10.0.10.34<0>
> ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_IB_HCA set to mlx5_2:1
> ts-34:1304096:1304096 [0] 420.577577 flagcxIbInit:545 FLAGCX TRACE NET/IB: [2] mlx5_2:uverbs2:1/RoCE speed=100000 context=0x5648b5743d80 pciPath=/sys/devices/pci0000:0a/0000:0a:01.0/0000:0b:00.0/0000:0c:03.0/0000:20:00.0 ar=0
> ts-34:1304096:1304096 [0] FLAGCX INFO NET/IB : Using [0]mlx5_2:1/RoCE [RO]; OOB ens3f0np0:10.0.10.34<0>
> ts-34:1304096:1304096 [0] FLAGCX INFO FLAGCX_TOPO_FILE environment variable not set
> ts-34:1304096:1304096 [0] FLAGCX INFO did not find local net for apu 0 in xml topo
> ts-34:1304096:1304096 [0] FLAGCX INFO APU 0 use net mlx5_2 specified in FLAGCX_USENET environment variable.
> [ts-34:1304096:0:1304096] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x60014eeeeef02)
> ==== backtrace (tid:1304096) ====
>  0  /lib/libucs.so.0(ucs_handle_error+0x2e4) [0x7fc4b2edfa84]
>  1  /lib/libucs.so.0(+0x23aac) [0x7fc4b2ee0aac]
>  2  /lib/libucs.so.0(+0x23c6a) [0x7fc4b2ee0c6a]
>  3  /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp16CreateDeviceAttrERKNS1_4attrE+0x2a5) [0x7fc4b4f80865]
>  4  /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp12CreateDeviceERKNS1_4attrE+0x36) [0x7fc4b4f82c16]
>  5  ../../build/lib/libflagcx.so(_Z23glooAdaptorCommInitRankPP15flagcxInnerCommiP14flagcxUniqueIdiP14bootstrapState+0x224) [0x7fc4ca358088]
>  6  ../../build/lib/libflagcx.so(flagcxCommInitRank+0x1831) [0x7fc4ca3242b4]
>  7  /data/FlagCX/test/perf/test_sendrecv(+0x2684) [0x5648875d5684]
>  8  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7fc4c9d8cd90]
>  9  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fc4c9d8ce40]
> 10  /data/FlagCX/test/perf/test_sendrecv(+0x23c5) [0x5648875d53c5]
> =================================
> [ts-34:1304096] *** Process received signal ***
> [ts-34:1304096] Signal: Segmentation fault (11)
> [ts-34:1304096] Signal code:  (-6)
> [ts-34:1304096] Failing at address: 0x13e620
> [ts-34:1304096] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fc4c9da5520]
> [ts-34:1304096] [ 1] /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp16CreateDeviceAttrERKNS1_4attrE+0x2a5)[0x7fc4b4f80865]
> [ts-34:1304096] [ 2] /data/gloo/build/install/lib/libgloo.so(_ZN4gloo9transport3tcp12CreateDeviceERKNS1_4attrE+0x36)[0x7fc4b4f82c16]
> [ts-34:1304096] [ 3] ../../build/lib/libflagcx.so(_Z23glooAdaptorCommInitRankPP15flagcxInnerCommiP14flagcxUniqueIdiP14bootstrapState+0x224)[0x7fc4ca358088]
> [ts-34:1304096] [ 4] ../../build/lib/libflagcx.so(flagcxCommInitRank+0x1831)[0x7fc4ca3242b4]
> [ts-34:1304096] [ 5] /data/FlagCX/test/perf/test_sendrecv(+0x2684)[0x5648875d5684]
> [ts-34:1304096] [ 6] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fc4c9d8cd90]
> [ts-34:1304096] [ 7] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fc4c9d8ce40]
> [ts-34:1304096] [ 8] /data/FlagCX/test/perf/test_sendrecv(+0x23c5)[0x5648875d53c5]
> [ts-34:1304096] *** End of error message ***
> /data/FlagCX/test/perf/gloo-mpi.sh: line 23: 1304096 Segmentation fault      (core dumped) /data/FlagCX/test/perf/test_sendrecv
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[35823,1],0]
>   Exit code:    139
> --------------------------------------------------------------------------
> ```

上述问题是否已经解决？

**Comment by tengqm** [comment]
The issue has been handled with a solution.
We haven't heard from the user for over 6+ months.
Let's assume that this issue has been resolved.
Please feel free to reopen if this is not the case.
